# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'smack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for smack

pod 'Alamofire', '~> 5.0.0-beta.2'
pod 'SwiftyJSON', '~> 4.0'
pod 'Socket.IO-Client-Swift', '~> 14.0.0'

end